baseURL: /
languageCode: en-us
defaultContentLanguage: en
title: Ayoub Fakir
theme: PaperMod
googleAnalytics: UA-123456789-1
enableGitInfo: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

taxonomies:
  tag: tags

permalinks:
  post: "post/:title"

imaging:
  quality: 99

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  description: "Everything Functional Programming and Distributed Systems (including the Bitcoin Ponzi Scheme) related."
  author: Ayoub Fakir
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  TocOpen: false
  comments: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  dateFormat: "Jan 2, 2006"

  socialIcons:
    - name: github
      url: "https://github.com/fakirAyoub"
    - name: linkedin
      url: "https://linkedin.com/in/afakir"
    - name: medium
      url: "https://medium.com/@AyoubFakir/"
    - name: twitter
      url: "https://twitter.com/the_cryptodata"
    - name: rss
      url: "/index.xml"
    - name: email
      url: "mailto:ayoub@fakir.dev"

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-icon.png"
    disableHLJS: true

  label:
    text: "Ayoub Fakir"

menu:
  main:
    - identifier: blog
      name: Blog
      url: /post/
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
    - identifier: search
      name: Search
      url: /search/
      weight: 4

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
    noClasses: false
    style: github-dark
    tabWidth: 4
  tableOfContents:
    endLevel: 4
    startLevel: 2
    ordered: false
