baseURL: /
languageCode: en-us
defaultContentLanguage: en
title: Ayoub Fakir
theme: cupper-hugo-theme
googleAnalytics: UA-123456789-1
enableGitInfo: true
#publishDir: post

taxonomies:
  tag: tags

permalinks:
  post:"post/:title"

imaging:
  quality: 99

params:
  description: A blog of someone who doesn't give a f*ck, but loves communication with a lot of good will towards others. Plus, my mom always says that I'm a good guy!
  homeMetaContent: Ayoub Fakir's Blog. 
  footer: Ayoub Fakir - 2020.
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true

menu:
  nav:
    - name: Blog
      url: /post
      weight: 1
    - name: Résumé
      url: /
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: About
      url: /about/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
