[build]
  publish = "public"
  command = "git submodule update --init --recursive && hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.150.2"
  HUGO_THEME = "PaperMod"
  HUGO_BASEURL = "/"
  GIT_LFS_ENABLED = "false"
