[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.60.1"
  HUGO_THEME = "papercss-hugo-theme"
  HUGO_BASEURL = "https://papercss-hugo-theme.netlify.com/"
