[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.60.1"
  HUGO_THEME = "cupper-hugo-theme"
  HUGO_BASEURL = "https://cupper-hugo-theme.netlify.com/"
